server:
  port: ${PORT:8080}

logging:
  level:
    '[org.atmosphere]': warn

spring:
  main:
    allow-bean-definition-overriding: true
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
        # options:
        # temperature: 0.5
        # top-k: 5
      embedding:
        model: nomic-embed-text
    vectorstore:
      milvus:
        client:
          host: 'localhost'
          port: 19530
          username: 'root'
          password: 'milvus'
        database-name: 'default'
        collection-name: 'vector_store'
        embedding-dimension: 768
        index-type: HNSW
        metric-type: COSINE
        auto-id: true
        id-field-name: 'id'
        initialize-schema: true
        index-parameters: '{"nlist": 16384}'

app:
  confluence-url: 'https://cypher-doing-ai.atlassian.net'

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.cypher
